//Authors: Johann Redhead and Tellon Smith
//Professor: Dr. Tina Johnson
//Course: CMPS 4143
//Date: 12/4/17
//Program: this program simulates the game of hangman in which the user is allowed to guess the letters of a word to be found

package hangman;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author T3L
 */
public class Game extends javax.swing.JFrame {
    //variables
    Hangman hangman = new Hangman();
    String fileName = "words.txt"; //text file containing words for game
    String icon = ".\\src\\hangman\\images\\icon.png";

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        
        hangman.initializeHangman(fileName);
        word_textfield.setHorizontalAlignment(JTextField.CENTER);
        
        try
        { 
            setIconImage(ImageIO.read(new File(icon)));
        } 
        catch (IOException e){
          e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start_button = new javax.swing.JButton();
        help_button = new javax.swing.JButton();
        about_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        a_button = new javax.swing.JButton();
        b_button = new javax.swing.JButton();
        c_button = new javax.swing.JButton();
        d_button = new javax.swing.JButton();
        e_button = new javax.swing.JButton();
        f_button = new javax.swing.JButton();
        g_button = new javax.swing.JButton();
        h_button = new javax.swing.JButton();
        i_button = new javax.swing.JButton();
        j_button = new javax.swing.JButton();
        k_button = new javax.swing.JButton();
        l_button = new javax.swing.JButton();
        m_button = new javax.swing.JButton();
        n_button = new javax.swing.JButton();
        o_button = new javax.swing.JButton();
        p_button = new javax.swing.JButton();
        q_button = new javax.swing.JButton();
        r_button = new javax.swing.JButton();
        s_button = new javax.swing.JButton();
        t_button = new javax.swing.JButton();
        u_button = new javax.swing.JButton();
        v_button = new javax.swing.JButton();
        w_button = new javax.swing.JButton();
        x_button = new javax.swing.JButton();
        y_button = new javax.swing.JButton();
        z_button = new javax.swing.JButton();
        score_label = new javax.swing.JLabel();
        slogan_label = new javax.swing.JLabel();
        triesLeft_label = new javax.swing.JLabel();
        bestScore_label = new javax.swing.JLabel();
        guessWord_button = new javax.swing.JButton();
        guessWord_textfield = new javax.swing.JTextField();
        word_textfield = new javax.swing.JTextField();
        logo_label = new javax.swing.JLabel();
        logo3_label = new javax.swing.JLabel();
        logo2_label = new javax.swing.JLabel();
        hangman_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman - Let's Play A Game");
        setResizable(false);

        start_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        start_button.setText("Start");
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });

        help_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        help_button.setText("Help");
        help_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_buttonActionPerformed(evt);
            }
        });

        about_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        about_button.setText("About");
        about_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_buttonActionPerformed(evt);
            }
        });

        exit_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit_button.setText("Exit");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        a_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a_button.setText("A");
        a_button.setEnabled(false);
        a_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_buttonActionPerformed(evt);
            }
        });

        b_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_button.setText("B");
        b_button.setEnabled(false);
        b_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buttonActionPerformed(evt);
            }
        });

        c_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c_button.setText("C");
        c_button.setEnabled(false);
        c_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_buttonActionPerformed(evt);
            }
        });

        d_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        d_button.setText("D");
        d_button.setEnabled(false);
        d_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_buttonActionPerformed(evt);
            }
        });

        e_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e_button.setText("E");
        e_button.setEnabled(false);
        e_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_buttonActionPerformed(evt);
            }
        });

        f_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        f_button.setText("F");
        f_button.setEnabled(false);
        f_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_buttonActionPerformed(evt);
            }
        });

        g_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        g_button.setText("G");
        g_button.setEnabled(false);
        g_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_buttonActionPerformed(evt);
            }
        });

        h_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h_button.setText("H");
        h_button.setEnabled(false);
        h_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h_buttonActionPerformed(evt);
            }
        });

        i_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        i_button.setText("I");
        i_button.setEnabled(false);
        i_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_buttonActionPerformed(evt);
            }
        });

        j_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j_button.setText("J");
        j_button.setEnabled(false);
        j_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_buttonActionPerformed(evt);
            }
        });

        k_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        k_button.setText("K");
        k_button.setEnabled(false);
        k_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_buttonActionPerformed(evt);
            }
        });

        l_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_button.setText("L");
        l_button.setEnabled(false);
        l_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_buttonActionPerformed(evt);
            }
        });

        m_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        m_button.setText("M");
        m_button.setEnabled(false);
        m_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_buttonActionPerformed(evt);
            }
        });

        n_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n_button.setText("N");
        n_button.setEnabled(false);
        n_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_buttonActionPerformed(evt);
            }
        });

        o_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        o_button.setText("O");
        o_button.setEnabled(false);
        o_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_buttonActionPerformed(evt);
            }
        });

        p_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p_button.setText("P");
        p_button.setEnabled(false);
        p_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_buttonActionPerformed(evt);
            }
        });

        q_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q_button.setText("Q");
        q_button.setEnabled(false);
        q_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q_buttonActionPerformed(evt);
            }
        });

        r_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r_button.setText("R");
        r_button.setEnabled(false);
        r_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_buttonActionPerformed(evt);
            }
        });

        s_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        s_button.setText("S");
        s_button.setEnabled(false);
        s_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_buttonActionPerformed(evt);
            }
        });

        t_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_button.setText("T");
        t_button.setEnabled(false);
        t_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_buttonActionPerformed(evt);
            }
        });

        u_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        u_button.setText("U");
        u_button.setEnabled(false);
        u_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_buttonActionPerformed(evt);
            }
        });

        v_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v_button.setText("V");
        v_button.setEnabled(false);
        v_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_buttonActionPerformed(evt);
            }
        });

        w_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        w_button.setText("W");
        w_button.setEnabled(false);
        w_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w_buttonActionPerformed(evt);
            }
        });

        x_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        x_button.setText("X");
        x_button.setEnabled(false);
        x_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_buttonActionPerformed(evt);
            }
        });

        y_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        y_button.setText("Y");
        y_button.setEnabled(false);
        y_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y_buttonActionPerformed(evt);
            }
        });

        z_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        z_button.setText("Z");
        z_button.setEnabled(false);
        z_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z_buttonActionPerformed(evt);
            }
        });

        score_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        score_label.setForeground(new java.awt.Color(0, 153, 0));
        score_label.setText("Score:");

        slogan_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        slogan_label.setForeground(new java.awt.Color(204, 0, 0));
        slogan_label.setText("LET'S PLAY A GAME");

        triesLeft_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        triesLeft_label.setForeground(new java.awt.Color(204, 0, 0));
        triesLeft_label.setText("Tries Left:");

        bestScore_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bestScore_label.setForeground(new java.awt.Color(0, 51, 255));
        bestScore_label.setText("Best:");

        guessWord_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        guessWord_button.setText("Guess Word");
        guessWord_button.setEnabled(false);
        guessWord_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessWord_buttonActionPerformed(evt);
            }
        });

        guessWord_textfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        guessWord_textfield.setEnabled(false);

        word_textfield.setEditable(false);
        word_textfield.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/images/logo.png"))); // NOI18N

        logo3_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/images/logo3.png"))); // NOI18N

        logo2_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/images/logo2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guessWord_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guessWord_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(646, 646, 646))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(score_label)
                            .addComponent(bestScore_label)
                            .addComponent(triesLeft_label))
                        .addGap(42, 42, 42))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hangman_label, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(word_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exit_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(help_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(about_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(logo2_label, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(slogan_label)
                                .addGap(132, 132, 132)))
                        .addComponent(logo3_label, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(o_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(s_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(u_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(k_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(w_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(z_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slogan_label))
                    .addComponent(logo2_label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo3_label, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(word_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(score_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bestScore_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(triesLeft_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(start_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(help_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(about_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(guessWord_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guessWord_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hangman_label, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(k_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(w_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //function initialized textboxes and images to the appropriate starting values
    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
        start_button.setText("New Game");
        hangman.initializeHangman(fileName);
        word_textfield.setText(hangman.getGameWord()); //draws '_' = to the length of the word
        resetControls();
        ImageIcon hangmanPic = new ImageIcon(".\\src\\hangman\\images\\"+hangman.getTriesLeft()+".png"); //draws the hanging post image as the first image
        hangman_label.setIcon(hangmanPic); //java has no picturebox, so set image as background of label
        score_label.setText("Score: "+ hangman.getScore());
        bestScore_label.setText("Best: "+ hangman.getBestScore());
        triesLeft_label.setText("Tries Left: "+ hangman.getTriesLeft());
    }//GEN-LAST:event_start_buttonActionPerformed

    private void help_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "HOW TO PLAY: \nHangman is a simple word guessing game. Players try to figure out an unknown word by guessing letters. \nIf too many letters which do not appear in the word are guessed, the player is hanged (and loses). \n\nSCORING: \nThe player receives 1 point for each correct letter guessed. when the word is completed or guessed correctly, \nthe player receives additional points equal to the amount of tries left. \n\nGood Luck! ", "Help", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_help_buttonActionPerformed

    private void about_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Hangman Ver. 1.0 \n\nCreated by: \nTellon Smith \nJohann Redhead", "About", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_about_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void a_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_buttonActionPerformed
        processInput('a', this.a_button);
    }//GEN-LAST:event_a_buttonActionPerformed

    private void b_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buttonActionPerformed
        processInput('b', this.b_button);
    }//GEN-LAST:event_b_buttonActionPerformed

    private void c_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_buttonActionPerformed
        processInput('c', this.c_button);
    }//GEN-LAST:event_c_buttonActionPerformed

    private void d_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_buttonActionPerformed
        processInput('d', this.d_button);
    }//GEN-LAST:event_d_buttonActionPerformed

    private void e_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_buttonActionPerformed
        processInput('e', this.e_button);
    }//GEN-LAST:event_e_buttonActionPerformed

    private void f_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_buttonActionPerformed
        processInput('f', this.f_button);
    }//GEN-LAST:event_f_buttonActionPerformed

    private void g_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_buttonActionPerformed
        processInput('g', this.g_button);
    }//GEN-LAST:event_g_buttonActionPerformed

    private void h_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h_buttonActionPerformed
        processInput('h', this.h_button);
    }//GEN-LAST:event_h_buttonActionPerformed

    private void i_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_buttonActionPerformed
        processInput('i', this.i_button);
    }//GEN-LAST:event_i_buttonActionPerformed

    private void j_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_buttonActionPerformed
        processInput('j', this.j_button);
    }//GEN-LAST:event_j_buttonActionPerformed

    private void k_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_buttonActionPerformed
        processInput('k', this.k_button);
    }//GEN-LAST:event_k_buttonActionPerformed

    private void l_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_buttonActionPerformed
        processInput('l', this.l_button);
    }//GEN-LAST:event_l_buttonActionPerformed

    private void m_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_buttonActionPerformed
        processInput('m', this.m_button);
    }//GEN-LAST:event_m_buttonActionPerformed

    private void n_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_buttonActionPerformed
        processInput('n', this.n_button);
    }//GEN-LAST:event_n_buttonActionPerformed

    private void o_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_buttonActionPerformed
        processInput('o', this.o_button);
    }//GEN-LAST:event_o_buttonActionPerformed

    private void p_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_buttonActionPerformed
        processInput('p', this.p_button);
    }//GEN-LAST:event_p_buttonActionPerformed

    private void q_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q_buttonActionPerformed
        processInput('q', this.q_button);
    }//GEN-LAST:event_q_buttonActionPerformed

    private void r_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_buttonActionPerformed
        processInput('r', this.r_button);
    }//GEN-LAST:event_r_buttonActionPerformed

    private void s_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_buttonActionPerformed
        processInput('s', this.s_button);
    }//GEN-LAST:event_s_buttonActionPerformed

    private void t_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_buttonActionPerformed
        processInput('t', this.t_button);
    }//GEN-LAST:event_t_buttonActionPerformed

    private void u_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_buttonActionPerformed
        processInput('u', this.u_button);
    }//GEN-LAST:event_u_buttonActionPerformed

    private void v_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_buttonActionPerformed
        processInput('v', this.v_button);
    }//GEN-LAST:event_v_buttonActionPerformed

    private void w_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w_buttonActionPerformed
        processInput('w', this.w_button);
    }//GEN-LAST:event_w_buttonActionPerformed

    private void x_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_buttonActionPerformed
        processInput('x', this.x_button);
    }//GEN-LAST:event_x_buttonActionPerformed

    private void y_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y_buttonActionPerformed
        processInput('y', this.y_button);
    }//GEN-LAST:event_y_buttonActionPerformed

    private void z_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z_buttonActionPerformed
        processInput('z', this.z_button);
    }//GEN-LAST:event_z_buttonActionPerformed

    //function checks to see if user-guessed word matches 
    private void guessWord_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessWord_buttonActionPerformed
        //if it matches
        if (hangman.checkGuessWord(guessWord_textfield.getText()))
        {
           hangman.setWinner(true); //set game state to a win, changes appropriate value and start a new game
           word_textfield.setText(hangman.getAnswer());
           JOptionPane.showMessageDialog(null, "Correct!", "", JOptionPane.PLAIN_MESSAGE);             
           hangman.updateScores();
           hangman.setWinner(false);
           hangman.getNextWord();
           hangman.resetTriesLeft();
           word_textfield.setText(hangman.getGameWord());
           resetControls();
        }
        else if (hangman.getTriesLeft() != 1)
        {
            hangman.decrementChancesLeft();
            
            //draw appropriate image based on number of tries consumed, appends a limb to the 'man' for each incorrect attempt
            ImageIcon hangmanPic = new ImageIcon(".\\src\\hangman\\images\\"+hangman.getTriesLeft()+".png"); 
            
            hangman_label.setIcon(hangmanPic);;
            JOptionPane.showMessageDialog(null, "Wrong!", "", JOptionPane.PLAIN_MESSAGE);
            guessWord_textfield.setText("");
        }
        else //all tries consumed, player loses the game
        {   
            JOptionPane.showMessageDialog(null, "Wrong!", "", JOptionPane.PLAIN_MESSAGE);
            word_textfield.setText(hangman.getAnswer());
            hangman.decrementChancesLeft();
            triesLeft_label.setText("Tries Left: "+ hangman.getTriesLeft());
            disableControls();
            ImageIcon hangmanPic = new ImageIcon(".\\src\\hangman\\images\\"+hangman.getTriesLeft()+".png");
            hangman_label.setIcon(hangmanPic);;
            JOptionPane.showMessageDialog(null, "GAME OVER! TRY AGAIN.", "", JOptionPane.PLAIN_MESSAGE);
        }
        score_label.setText("Score: "+ hangman.getScore());
        bestScore_label.setText("Best: "+ hangman.getBestScore());
        triesLeft_label.setText("Tries Left: "+ hangman.getTriesLeft());
    }//GEN-LAST:event_guessWord_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }
    
    protected void processInput(char guessLetter, JButton button)
    {
        button.setEnabled(false); //disable buttons so it can't be selected as another guess
        if (hangman.checkGuessLetter(guessLetter)) //check to see if letter is part of the word to be guessed
        {
            hangman.updateGameWord(guessLetter); //adds the letter the user guessed to the textfield
            if (hangman.checkGameWord()) //checks to see if new word matches the word to be guessed
            {                
                hangman.setWinner(true);
                word_textfield.setText(hangman.getAnswer());
                JOptionPane.showMessageDialog(null, "Correct!", "", JOptionPane.PLAIN_MESSAGE);             
                hangman.updateScores();
                hangman.setWinner(false);
                hangman.getNextWord();
                hangman.resetTriesLeft();
                word_textfield.setText(hangman.getGameWord());
                resetControls();
            }
            else //if word doesn't match yet, update the player score
            {
                word_textfield.setText(hangman.getGameWord());
                hangman.updateScores();
            }
        }
        else if (hangman.getTriesLeft() != 1) //if no match, decerement tries and add new limb to the man
        {
            hangman.decrementChancesLeft();
            ImageIcon hangmanPic = new ImageIcon(".\\src\\hangman\\images\\"+hangman.getTriesLeft()+".png");
            hangman_label.setIcon(hangmanPic);;
            button.setForeground(Color.red);            
        }
        else //user consumed all their tries, display the word they were guessing and end the game
        {            
            word_textfield.setText(hangman.getAnswer());
            hangman.decrementChancesLeft();
            triesLeft_label.setText("Tries Left: "+ hangman.getTriesLeft());
            disableControls();
            ImageIcon hangmanPic = new ImageIcon(".\\src\\hangman\\images\\"+hangman.getTriesLeft()+".png");
            hangman_label.setIcon(hangmanPic);;
            JOptionPane.showMessageDialog(null, "GAME OVER! TRY AGAIN.", "", JOptionPane.PLAIN_MESSAGE);
        }
        score_label.setText("Score: "+ hangman.getScore());
        bestScore_label.setText("Best: "+ hangman.getBestScore());
        triesLeft_label.setText("Tries Left: "+ hangman.getTriesLeft());
    }
    
    protected void resetControls()
    {
        word_textfield.setEnabled(true);
        guessWord_textfield.setEnabled(true);
        guessWord_textfield.setText("");
        guessWord_button.setEnabled(true);
        a_button.setEnabled(true);
        a_button.setForeground(Color.black);
        b_button.setEnabled(true);
        b_button.setForeground(Color.black);
        c_button.setEnabled(true);
        c_button.setForeground(Color.black);
        d_button.setEnabled(true);
        d_button.setForeground(Color.black);
        e_button.setEnabled(true);
        e_button.setForeground(Color.black);
        f_button.setEnabled(true);
        f_button.setForeground(Color.black);
        g_button.setEnabled(true);
        g_button.setForeground(Color.black);
        h_button.setEnabled(true);
        h_button.setForeground(Color.black);
        i_button.setEnabled(true);
        i_button.setForeground(Color.black);
        j_button.setEnabled(true);
        j_button.setForeground(Color.black);
        k_button.setEnabled(true);
        k_button.setForeground(Color.black);
        l_button.setEnabled(true);
        l_button.setForeground(Color.black);
        m_button.setEnabled(true);
        m_button.setForeground(Color.black);
        n_button.setEnabled(true);
        n_button.setForeground(Color.black);
        o_button.setEnabled(true);
        o_button.setForeground(Color.black);
        p_button.setEnabled(true);
        p_button.setForeground(Color.black);
        q_button.setEnabled(true);
        q_button.setForeground(Color.black);
        r_button.setEnabled(true);
        r_button.setForeground(Color.black);
        s_button.setEnabled(true);
        s_button.setForeground(Color.black);
        t_button.setEnabled(true);
        t_button.setForeground(Color.black);
        u_button.setEnabled(true);
        u_button.setForeground(Color.black);
        v_button.setEnabled(true);
        v_button.setForeground(Color.black);
        w_button.setEnabled(true);
        w_button.setForeground(Color.black);
        x_button.setEnabled(true);
        x_button.setForeground(Color.black);
        y_button.setEnabled(true);
        y_button.setForeground(Color.black);
        z_button.setEnabled(true);
        z_button.setForeground(Color.black);
    }
    
    protected void disableControls()
    {
        word_textfield.setEnabled(false);
        guessWord_textfield.setEnabled(false);
        guessWord_button.setEnabled(false);
        a_button.setEnabled(false);
        b_button.setEnabled(false);
        c_button.setEnabled(false);
        d_button.setEnabled(false);
        e_button.setEnabled(false);
        f_button.setEnabled(false);
        g_button.setEnabled(false);
        h_button.setEnabled(false);
        i_button.setEnabled(false);
        j_button.setEnabled(false);
        k_button.setEnabled(false);
        l_button.setEnabled(false);
        m_button.setEnabled(false);
        n_button.setEnabled(false);
        o_button.setEnabled(false);
        p_button.setEnabled(false);
        q_button.setEnabled(false);
        r_button.setEnabled(false);
        s_button.setEnabled(false);
        t_button.setEnabled(false);
        u_button.setEnabled(false);
        v_button.setEnabled(false);
        w_button.setEnabled(false);
        x_button.setEnabled(false);
        y_button.setEnabled(false);
        z_button.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a_button;
    private javax.swing.JButton about_button;
    private javax.swing.JButton b_button;
    private javax.swing.JLabel bestScore_label;
    private javax.swing.JButton c_button;
    private javax.swing.JButton d_button;
    private javax.swing.JButton e_button;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton f_button;
    private javax.swing.JButton g_button;
    private javax.swing.JButton guessWord_button;
    private javax.swing.JTextField guessWord_textfield;
    private javax.swing.JButton h_button;
    private javax.swing.JLabel hangman_label;
    private javax.swing.JButton help_button;
    private javax.swing.JButton i_button;
    private javax.swing.JButton j_button;
    private javax.swing.JButton k_button;
    private javax.swing.JButton l_button;
    private javax.swing.JLabel logo2_label;
    private javax.swing.JLabel logo3_label;
    private javax.swing.JLabel logo_label;
    private javax.swing.JButton m_button;
    private javax.swing.JButton n_button;
    private javax.swing.JButton o_button;
    private javax.swing.JButton p_button;
    private javax.swing.JButton q_button;
    private javax.swing.JButton r_button;
    private javax.swing.JButton s_button;
    private javax.swing.JLabel score_label;
    private javax.swing.JLabel slogan_label;
    private javax.swing.JButton start_button;
    private javax.swing.JButton t_button;
    private javax.swing.JLabel triesLeft_label;
    private javax.swing.JButton u_button;
    private javax.swing.JButton v_button;
    private javax.swing.JButton w_button;
    private javax.swing.JTextField word_textfield;
    private javax.swing.JButton x_button;
    private javax.swing.JButton y_button;
    private javax.swing.JButton z_button;
    // End of variables declaration//GEN-END:variables
}
